### PR TITLE
Upgrade to gradle 6.1.1

### PR DESCRIPTION
**Pull request by oguzkocer**
This PR updates gradle wrapper to `6.1.1`. The wrapper file changes are created automatically by the `gradle wrapper --gradle-version 6.1.1` command.

[As of Android Gradle Plugin 3.1 `buildToolsVersion` is not necessary anymore as the plugin uses the minimum required version by default.](https://developer.android.com/studio/releases/gradle-plugin#3-1-0) If this value is off, it creates warnings such as the one below, so it's best to just remove it. 

```
WARNING: The specified Android SDK Build Tools version (29.0.1) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.0.1.
Android SDK Build Tools 29.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '29.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
```

**To test:**

Running `./gradlew build` and verifying the build is successful should be enough.

---

I don't think this will matter, but it might be best to approve this PR but not merge it until we are ready to merge the [WPAndroid PR](https://github.com/wordpress-mobile/WordPress-Android/pull/12896) which is close to be ready for review. I'll leave the decision for that to you @aforcier & @mzorz!

### CODE REVIEW

**Comment by oguzkocer** [comment]
@aforcier @mzorz We are almost ready with the Gradle upgrade for WPAndroid, so I am adding Jeremy to the reviewers as we might be able to get all of these updates done today. Considering there is no code change in the library, I am hoping that this is OK with you two.

**Comment by mzorz** [comment]
@oguzkocer I'll get to it in a few minutes 👍

**Comment by mzorz** [comment]
After checking the changeset, comparing to release notes and not finding anything weird, I've run the standalone example app and also tested this PR with WPAndroid with and without the changes in the [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/12896) indicated above in the [description](https://github.com/Automattic/stories-android/pull/518#issue-486964173). On WPAndroid's `develop` I was able to build and run several different flavors of WPAndroid, smoke tested it and didn't find anything weird in the process (except for the warning mentioned above which is expected when not all the libraries have been yet updated).

However, on the branch corresponding to WPAndroid's  https://github.com/wordpress-mobile/WordPress-Android/pull/12896 I get the following error when running `./gradlew assembleZalphaDebug`:

```
> Task :WordPress:stripZalphaDebugDebugSymbols FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':WordPress:stripZalphaDebugDebugSymbols'.
> No version of NDK matched the requested version 21.0.6113669. Versions available locally: 20.0.5594570
```

> I don't think this will matter, but it might be best to approve this PR but not merge it until we are ready to merge the WPAndroid PR which is close to be ready for review. I'll leave the decision for that to you @aforcier & @mzorz!

I'm not sure this is related to the [NDK version comment found in here](https://developer.android.com/studio/releases/gradle-plugin#behavior_changes), given the versions the error above states are a difference between 21.x and 20.x (and the comment talks about the need to use even an earlier version for a purpose that looks totally unrelated to our goals).

Before approving I'd like to learn more about that other error (why it appears or if I need to do anything here), wdyt @oguzkocer ? I would otherwise be OK with the changes here if everything continued to work.

**Comment by oguzkocer** [comment]
@mzorz That sounds like a local environment issue, but since I don't get the same error and I don't know much about the particulars of the issue, I am not sure how best to proceed. 🤔 

@aforcier @jkmassel Could you try the same task in your local machine to see if you can reproduce the issue?

**Review by jkmassel — APPROVED** [review]
This worked fine for me – got some warnings, but no failures. I think I'm just missing some NDK tooling for slicing up the binary:

```
Unable to strip library '/Users/jkmassel/Projects/stories-android/app/build/intermediates/merged_native_libs/debug/out/lib/arm64-v8a/libevent-2.1.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
```

We talked about the code in our video chat, so no concerns from my side – I'm ok to ship it with the other PR when y'all are 😃

**Comment by aforcier** [comment]
I'm trying to test this but I'm having a lot of trouble building WPAndroid right now for unrelated reasons.

```
Task :@wordpress_react-native-bridge:npmInstall
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://registry.npmjs.org/cosmiconfig failed, reason: connect ECONNREFUSED 127.0.0.1:80
npm ERR!     at ClientRequest.<anonymous> (/private/var/folders/h8/5zrz8r0j3gq81p9d956mqdhh0000gn/T/jsbundle/null/npm/npm-v6.14.5/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:315:20)
npm ERR!     at onerror (/private/var/folders/h8/5zrz8r0j3gq81p9d956mqdhh0000gn/T/jsbundle/null/npm/npm-v6.14.5/lib/node_modules/npm/node_modules/agent-base/index.js:101:9)
npm ERR!     at callbackError (/private/var/folders/h8/5zrz8r0j3gq81p9d956mqdhh0000gn/T/jsbundle/null/npm/npm-v6.14.5/lib/node_modules/npm/node_modules/agent-base/index.js:123:5)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR!  FetchError: request to https://registry.npmjs.org/cosmiconfig failed, reason: connect ECONNREFUSED 127.0.0.1:80
npm ERR!     at ClientRequest.<anonymous> (/private/var/folders/h8/5zrz8r0j3gq81p9d956mqdhh0000gn/T/jsbundle/null/npm/npm-v6.14.5/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:315:20)
npm ERR!     at onerror (/private/var/folders/h8/5zrz8r0j3gq81p9d956mqdhh0000gn/T/jsbundle/null/npm/npm-v6.14.5/lib/node_modules/npm/node_modules/agent-base/index.js:101:9)
npm ERR!     at callbackError (/private/var/folders/h8/5zrz8r0j3gq81p9d956mqdhh0000gn/T/jsbundle/null/npm/npm-v6.14.5/lib/node_modules/npm/node_modules/agent-base/index.js:123:5)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
npm ERR!   type: 'system',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   parent: '@wordpress/eslint-plugin'
npm ERR! }
```

Looking into it but it's taken a while with no progress already and in the meantime I don't want to block this unnecessarily.

It sounds like @mzorz is able to build this library fine (and so am I) and the environment issue is in WPAndroid - so this PR seems okay.

However I'd recommend getting several people to try that PR to see if others experience the same issue there.

**Comment by aforcier** [comment]
Got it building, no build error for me either, just this warning:

> WARNING: Compatible side by side NDK version was not found. Default is 21.0.6113669.
Compatible side by side NDK version was not found. Default is 21.0.6113669.
Unable to strip the following libraries, packaging them as they are: libc++_shared.so, libfb.so, libfolly_futures.so, libfolly_json.so, libgifimage.so, libglog.so, libglog_init.so, libhermes-executor-release.so, libhermes.so, libimagepipeline.so, libjnidispatch.so, libjsijniprofiler.so, libjsinspector.so, libnative-filters.so, libnative-imagetranscoder.so, libreactnativeblob.so, libreactnativejni.so, libsentry-android.so, libsentry.so, libsodium.so, libyoga.so.

@mzorz do you maybe have an NDK version configured in the project settings? Mine is blank which I guess is the default.

**Comment by mzorz** [comment]
> @mzorz That sounds like a local environment issue

Seemed like so and confirmed it was, yes

> @mzorz do you maybe have an NDK version configured in the project settings? Mine is blank which I guess is the default.

Couldn't find  a proper `ndk.dir` entry set but apparently I did had set a [specific version of the NDK on AS ](https://developer.android.com/studio/projects/install-ndk#specific-version)(don't know / recall exactly why) as can be seen here:
Screen Shot 2020-09-16 at 07 10 22

Confirmed everything works after installing the requested NDK version locally.

Approving & merging 👍

**Review by mzorz — APPROVED** [review]
Thank you all for the extra set of 👀 !

LGTM :shipit:

**Comment by oguzkocer** [comment]
@aforcier The WPAndroid PR worked for 4 of us so far, I think that it is good enough to merge. However, I'll mention this issue on Slack, so if it comes up for anyone, we can address it quickly.

Thank you all for the review/test! 🙇

**Pull request merged**
